### ISSUE TITLE
I have some legacy NEI event sites, are y'all interested in them?

### ISSUE THREAD

**Issue by LuchoTurtle** [Nucleo-Estudantes-Informatica-ISEP/.github#1]
Hey NEI 👋  @Eduardoooxd  @ricardo177m 

Figured I'd open the issue here, seemed more appropriate. 

Props on setting up NEI's own organization on Github and expanding https://github.com/Nucleo-Estudantes-Informatica-ISEP/antirecurso, it was sorely needed!

I was an old member a few years back and I have a private repo with some code from past events. Would y'all be interested in them? If so, invite me to the org or something, and I'll transfer the repo to your org so you can do whatever you want with it 😄 (even if it's just to be archived and for historical reasons).

Here's the repo -> https://github.com/LuchoTurtle/nei-stuff

**Comment by eduardocoutodev** [comment]
Thanks for the contact, 
I answered on the open issue of[ antirecurso repo](https://github.com/Nucleo-Estudantes-Informatica-ISEP/antirecurso/issues/39).
